### ISSUE TITLE
Security vulnerability from transient loader-utils package

### ISSUE THREAD

**Issue by williantenfen** [apeschar/esbuild-vue#20]
```
esbuild-vue@1.2.2 requires loader-utils@^0.2.16 via a transitive dependency on generic-names@1.0.3
```

Looks like: `@vue/component-compiler@^4.2.4` ->  `postcss-modules-sync "^1.0.0"` ->  `generic-names@^1.0.2` -> `loader-utils "^0.2.16"`

Is there a way to move from `@vue/component-compiler` to `@vue/compiler-sfc": "2.7.14" ` ?  I guess that would remove dependency from postcss-modules-sync

**Comment by apeschar** [comment]
> Is there a way to move from @vue/component-compiler to @vue/compiler-sfc": "2.7.14" ?

It's probably possible and not too hard, but I'm not going to do it.  A PR that does this and keeps all (or most) current functionality working is welcome, of course.

I will close this issue now as I don't believe there is any way we can act on it in the scope of this repository without rewriting most of the functionality.
