### ISSUE TITLE
Compiling vue SFC typescript files provides incorrect output

### ISSUE THREAD

**Issue by Havunen** [apeschar/esbuild-vue#25]
**Having typescript script language and components as classes outputs incorrect result**

```vue
<template>
  <transition name="modal">
    <div
    </div>
  </transition>
</template>

<script lang="ts">
import { Vue, Prop } from 'vue-property-decorator'
import { $bus } from '@/common/services/bus'

export default class ConfirmModal extends Vue {
  bus: Vue = $bus
  @Prop(String) emit!: string
  @Prop(Object) emitValue!: object
  @Prop(Object) translationParams!: object
  @Prop(Boolean) emitToLocal!: boolean
```

> ✘ [ERROR] Experimental decorators can only be used with class declarations in TypeScript

    VueApp/template/views/eNotice/components/modals/ConfirmModal.vue:60:2:
      60 │   @Prop(Object) modalTexts!: ConfirmModalTexts
         ╵   ^

  This is a class expression, not a class declaration:

    VueApp/template/views/eNotice/components/modals/ConfirmModal.vue:54:23:
      54 │ const __vue_script__ = class ConfirmModal extends Vue {

**Another error I'm seeing is this:**

> ✘ [ERROR] Experimental decorators can only be used with class declarations in TypeScript

    VueApp/template/views/eNotice/components/modals/ConfirmModal.vue:59:2:
      59 │   @Prop(Function) cancelCallback!: () => void

It seems the compiler does not honor **<script lang="ts">** and class (export /assignment) is not correctly compiled

**Comment by apeschar** [comment]
It's a known issue with the way the Vue compiler works.

https://github.com/apeschar/esbuild-vue/issues/19

I don't intend to spend any time on this right now, but PRs are welcome.
