### ISSUE TITLE
Can't find stylesheet to import.

### ISSUE THREAD

**Issue by echjordan0** [apeschar/esbuild-vue#28]
Hello,
Thanks so much for this plugin.
It seems I'm unable to to use a sass stylesheet imported from node modules with the plugin. I've tried adding the esbuild-sass-plugin with various configurations but they don't seem to have any affect. For context, I'm using the plugin as part of the native federation implementation for vite ([example](https://www.npmjs.com/package/@softarc/native-federation#augment-your-build-process)). I'm fairly confident this is an issue with esbuild-vue because that's where the error seems to originate but let me know if I should take my question to the [vite plugin](https://github.com/module-federation/vite) repo.

I get:
```
✘ [ERROR] Can't find stylesheet to import.
   ╷
71 │ @import '@internal/citrus-ui/src/styles/core.scss';
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/Index.vue 71:9  root stylesheet [plugin vue]
```

I've tried:
```js
      adapter: createEsBuildAdapter({
        plugins: [
          sassPlugin({
            importMapper: (path) => path.replace(/^@internal\//, './node_modules/@internal/'),
          }),
          pluginVue(),
        ],
      }),
```

```js
      adapter: createEsBuildAdapter({
        plugins: [
          sassPlugin({
            includePaths: ['node_modules/@internal/citrus-ui/src/styles/'],
            importer: createImporter(),
          }),
          pluginVue(),
        ],
      }),
```

**Comment by spiderpug** [comment]
I'm encountering the same issue. Did you happen to find a solution yet?

My investigations showed that the `importMapper` method is not called for me for these `@import` requests.

**Comment by echjordan0** [comment]
I did not find a solution -- I ended up going with a different module federation plugin due to the level of manual configuration required with the one that was using esbuild-vue.
